# Generated by Django 6.1.1 on 2026-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
